CREATE TABLE F_COLLAPSE_FNLNE_ERRLOG
  (
    TABLE_NAME  VARCHAR2 ( 27 ),
    ERR_CODE    VARCHAR2 ( 10 ),
    ERR_MSG     VARCHAR2 ( 255 ),
    CREATED_ON  TIMESTAMP ( 6 )
  ) NOLOGGING;
CREATE TABLE F_COLLAPSE_FNLNE_SUSP
  ( CONT_ID NUMBER ( 19 )
  ) NOLOGGING ;
CREATE TABLE F_COLLAPSE_FNLNE_SUSP_R
  ( CONT_ID NUMBER ( 19 )
  ) NOLOGGING ;
CREATE TABLE F_COLLAPSE_FNLNE_NONSUSP
  ( CONT_ID NUMBER ( 19 )
  ) NOLOGGING;
CREATE TABLE F_COLLAPSE_FNLNE_MATCH
  (
    SUSPECT_GROUP_ID  NUMBER ( 19 ),
    CONT_ID           NUMBER ( 19 ),
    SUSPECT_IND       VARCHAR2 ( 1 ),
    CONTACT_METHOD_ID NUMBER ( 19 )
  )
  NOLOGGING ;
CREATE TABLE F_COLLAPSE_FNLNE_ADDR
  (
    CONT_ID        NUMBER ( 19 ),
    ADDRESS_ID     NUMBER ( 19 ),
    XADDRESS_TP_CD NUMBER ( 19 )
  )
  NOLOGGING;
CREATE TABLE F_COLLAPSE_FNLNE_CONTMETH
  (
    CONT_ID           NUMBER ( 19 ),
    CONTACT_METHOD_ID NUMBER ( 19 ),
    CONT_METH_CAT_CD  NUMBER ( 19 )
  )
  NOLOGGING;
CREATE TABLE F_COLLAPSE_FNLNE_ACCT
  (
    CONT_ID        NUMBER ( 19 ),
    ACCOUNT_NUM    NUMBER ( 30 ),
    XACCOUNT_TP_CD NUMBER ( 19 )
  )
  NOLOGGING; 
CREATE TABLE F_COLLAPSE_FNLNE_ELIG
  ( CONT_ID NUMBER ( 19 )
  ) NOLOGGING;
CREATE TABLE F_COLLAPSE_FNLNE_MINATTRIB
  ( CONT_ID NUMBER ( 19 )
  ) NOLOGGING;
CREATE TABLE F_COLLAPSE_FNLNE_STAGE
  (
    F_COLLAPSE_FNLNE_STAGE_ID NUMBER ( 19 ),
    SUSPECT_GROUP_ID      NUMBER ( 19 ),
    SUSPECT_CONT_ID       NUMBER ( 19 ),
    CONT_ID               NUMBER ( 19 ),
    CREATED_DT            TIMESTAMP ( 6 ),
    SUSPECT_GROUP_COUNT   NUMBER ( 19 ),
    SUSPECT_ROWNUM        NUMBER ( 19 ),
    CONSTRAINT F_COLLAPSE_FNLNE_STAGE_PK PRIMARY KEY ( F_COLLAPSE_FNLNE_STAGE_ID )
  )
  NOLOGGING ;
CREATE MATERIALIZED VIEW LOG ON F_COLLAPSE_FNLNE_STAGE
WITH PRIMARY KEY;
CREATE MATERIALIZED VIEW MV_F_COLLAPSE_FNLNE
  NOLOGGING 
  NOCACHE 
  BUILD IMMEDIATE 
  REFRESH COMPLETE ON DEMAND
AS
WITH F_COLLAPSE_CONT_ID AS
  (
    SELECT F_CONT_ID AS CONT_ID FROM FORCE_COLLAPSE
    UNION ALL
    SELECT F_SUSPECT_CONT_ID AS CONT_ID FROM FORCE_COLLAPSE
  )
SELECT
  /*+ PARALLEL(AUTO) */
  FCS.F_COLLAPSE_FNLNE_STAGE_ID,
  FCS.SUSPECT_CONT_ID,
  FCS.CONT_ID,
  FCS.SUSPECT_GROUP_COUNT,
  FCS.SUSPECT_ROWNUM
FROM F_COLLAPSE_FNLNE_STAGE FCS
WHERE NOT EXISTS
  (
    SELECT 1 FROM F_COLLAPSE_CONT_ID FCC WHERE FCS.SUSPECT_CONT_ID = FCC.CONT_ID
  )
AND NOT EXISTS
  (
    SELECT 1 FROM F_COLLAPSE_CONT_ID FCC WHERE FCS.CONT_ID = FCC.CONT_ID
  ) ;